### ISSUE TITLE
Poder selecionar as matérias que já cursou

### ISSUE THREAD

**Issue by joaoguilac** [nandagb/Grade-Curricular-UFRN---BTI#3]
Uma sugestão de implementação seria mostrar as matérias que a pessoa pode pagar (as matérias ficariam com a cor amarelo, por exemplo) e as que não podia pagar (as matérias ficariam em vermelho, por exemplo). Aí a pessoa poderia selecionar as matérias que já pagou (só poderia selecionar as que ela poderia pagar, no caso as em amarelo, e quando selecionasse ficaria verde, por exemplo, indicando que já foi pago). Ao selecionar matérias que pagou, dependendo das matérias selecionadas, as vermelhas que possuem pré-requisito poderiam mudar de vermelho (não pode pagar) para amarelo (pode pagar).

OBS: as cores foi só pra facilitar a explicação, poderia usar outro tipo de identificador.

**Comment by nandagb** [comment]
atualização: agora você pode! 
Não foi implementado para todas as grades ainda, mas já está disponível para a grade geral do BTI
